Scene sketch
membraneframework-labs/membrane_video_compositor_plugin pull request #41
Opened 2022-09-21 15:30 UTC by Janix4000

Scene core and transformations pipeline, for more advance video composition

2022-10-11 08:57 UTC, DominikWolek requested changes

2022-10-11 08:57 UTC, DominikWolek commented on lib/membrane/video_compositor/scene/video.ex
> +  defstruct components: %{}, state: %{position: %Position{x: 0, y: 0}}
How is video connected to the input pads of the Compositor?

2022-10-11 08:57 UTC, DominikWolek commented on lib/membrane/video_compositor/scene/video.ex
> +  @spec update(t, Manager.t(), context :: any) :: {:ok, t} | {:error, error_t}
Either stick to the `type` or `type()` for zero-arrity types. This applies to the whole PR, of course

2022-10-11 08:57 UTC, DominikWolek commented on lib/membrane/video_compositor/scene.ex
> +  @type components_t :: keyword(component_t())
I don't like video id being a number. It conveys no useful information. I would understand if `add_video` would not take a id as an argument and this number would be assigned automatically (as in: next free number). Why not `any()` (like a https://hexdocs.pm/membrane_core/Membrane.Element.html#t:name_t/0) or `atom()`?

2022-10-11 08:57 UTC, DominikWolek commented on lib/membrane/video_compositor/scene.ex
> +        ]
IMO `scene_spec` is better name, instead of scene description. What do you think?

2022-10-11 08:57 UTC, DominikWolek commented on lib/membrane/video_compositor/scene.ex
> +          scenes: %{required(atom()) => t()}
Why do videos have their type for `id_t`, and scenes don't?

2022-10-11 08:57 UTC, DominikWolek commented on lib/membrane/video_compositor/scene.ex
> +    end
I'm not found of that style of handling errors, but I think I can understand reasons why you wrote it like that. Maybe we could discuss that matter with the rest of the them, perhaps on the architecture brainstorming meeting?

2022-11-08 09:07 UTC, WojciechBarczynski commented
@Janix4000 @DominikWolek Shouldn't we close this PR?

2023-01-05 08:51 UTC, closed without merging