Add z-value sorting when composing videos.
membraneframework-labs/membrane_video_compositor_plugin pull request #50
Opened 2022-10-11 15:26 UTC by jerzywilczek

I have to go for now, so this is quite barebones in terms of the API. I do not realy know whether adding z as a field in `Position` is a good solution.

2022-10-12 11:32 UTC, DominikWolek commented on lib/membrane/video_compositor/implementations/common.ex
> +    {:ok, %__MODULE__{x: x, y: y, z: z}}
Shouldn't we check z here if it is in <-1,1> range?

2022-10-12 14:09 UTC, Janix4000 requested changes

2022-10-12 14:09 UTC, Janix4000 commented on lib/membrane/video_compositor/frame_compositor.ex
> +              position :: {x :: non_neg_integer(), y :: non_neg_integer(), z :: float()}
1. In many 2D frameworks z-index is an integer
3. At Elixir's level of abstraction 'third dimension' has no sense, it should be a separate field

2022-10-24 12:02 UTC, Janix4000 requested changes
Minor changes and z ordering

2022-10-25 09:39 UTC, Janix4000 requested changes
Small fixes

2022-10-25 09:39 UTC, Janix4000 commented on lib/membrane/video_compositor/implementations/common.ex
> +    {:ok, %__MODULE__{x: x, y: y, z: z}}
Maybe we should raise exceptions, instead of the `{:ok | :error, ...}` pattern, @DominikWolek what do you think?

2022-10-25 09:39 UTC, Janix4000 commented on native/membrane_videocompositor_wgpu/src/lib.rs
> +            },
```suggestion
            z: 1.0 - max(position.z, 1e-7)
```

2022-10-25 12:10 UTC, Janix4000 approved these changes

2022-10-25 12:11 UTC, merged