Remove the OpenGL-based compositor.
membraneframework-labs/membrane_video_compositor_plugin pull request #52
Opened 2022-10-13 09:38 UTC by jerzywilczek

2022-10-13 09:55 UTC, DominikWolek commented on .vscode/settings.json
>          "native/membrane_videocompositor_wgpu/Cargo.toml"
Maybe we should rename the forlder to the `native/membrane_video_compositor/`

2022-10-18 12:50 UTC, WojciechBarczynski requested changes
Remove OpenGL in demos and benchmarks as well

2022-10-25 10:20 UTC, WojciechBarczynski approved these changes
lgtm

2022-10-25 12:20 UTC, Janix4000 commented on benchmark/lib/benchee/h264_pipeline.exs
> +        # FIXME: inputting the implementations manually is a really bad design and I hate it ~jerzy
+1

2022-10-25 12:20 UTC, Janix4000 commented on benchmark/lib/benchee/raw_pipeline.exs
> +        # FIXME: inputting the implementations manually is a really bad design and I hate it ~jerzy
+1

2022-10-25 12:22 UTC, Janix4000 commented on lib/membrane/video_compositor/common.ex
>    Position relative to the top right corner of the viewport, in pixels.
Remember `right` -> `left`

2022-10-25 12:24 UTC, Janix4000 approved these changes

2022-10-25 12:24 UTC, merged