Ms 274 live queueing video frames
membraneframework-labs/membrane_video_compositor_plugin pull request #60
Opened 2022-11-14 17:00 UTC by jerzywilczek

This patch makes use of Membrane timers to allow live operation of the
compositor:

 * A timer with interval equal to seconds / frames is started when the element starts operating.

 * Whenever a frame is composed naturally (when all vidoes have frames ready for composition) the timer is restarted.

 * When the timer ticks, a frame is forcibly rendered, using previous frames as fallback in cases where we don't have a frame ready.

 * To protect against stale frames clogging the front of the queue, whenever a frame is rendered stale frames are removed from the front of the queue.
 
 It also adds tests:
 
 *  A new element, `BadConnectionEmulator`, was added to simulate delays and
packet loss.

 * The `ComposeMultipleInputs` pipeline was altered to allow introducing an
additional filter between the decoder and the compositor.

 * A new test was added (`packet_loss.ex`). It is completely analogous to
the h264 pipeline test, but uses the `BadConnectionEmulator` and sets
the compositor to live mode.

These tests don't verify much unfortunately. Since some frames are
randomly dropped or delayed, there is no reference result to compare to.

2022-11-15 14:28 UTC, Janix4000 commented on lib/membrane/compositor_element.ex
>                ]
Does `live` option trigger frames dropping? I think it should be better described.

2022-11-15 14:51 UTC, Janix4000 requested changes

2022-11-16 16:08 UTC, DominikWolek requested changes

2022-11-16 16:08 UTC, DominikWolek commented on lib/membrane/compositor_element.ex
> +      end
```suggestion
     actions = if all_input_pads_received_end_of_stream?(context.pads) do
      stop = if state.live, do: [stop_timer: :render_frame], else: []
      [end_of_stream: :output] ++ stop
    else
      []
    end

    {{:ok, actions}, state}
```
Obviously it is also for the line above and below, but GitHub don't let do this proper way.

2022-11-17 14:59 UTC, DominikWolek approved these changes

2022-11-17 14:59 UTC, DominikWolek commented on lib/membrane/compositor_element.ex
> +     If the frames arrive later, they will be dropped.
Maybe mention updating the fallback frame

2022-11-17 14:59 UTC, DominikWolek commented on lib/membrane/compositor_element.ex
> +              live: [
I know we kept calling this feature "live queueing" but I wonder if real-time isn't a better name for this.

2022-11-21 08:32 UTC, Janix4000 approved these changes
Good job

2022-11-21 13:51 UTC, merged