Early release version
membraneframework-labs/membrane_video_compositor_plugin pull request #65
Opened 2022-11-24 14:35 UTC by WojciechBarczynski

In early release implements some features, that are not meant to be in the final version / are meant to be implemented in another way, but since we need VC right now, I implemented them this way.
Features added:
1. z_value option in input pad options
2. scale option in input pad options
3. white background when there is no video in part of an output frame

2022-11-24 14:47 UTC, WojciechBarczynski commented
@DominikWolek Can you check it out?

2022-11-30 12:57 UTC, Janix4000 requested changes
I did not view the edge rounding shader.

Some minor changes

2022-11-30 12:57 UTC, Janix4000 commented on lib/membrane/compositor_element.ex
> +      pts_offsets: %{},
I think you should gather all of these properties into the `VideoOptions` struct

2022-11-30 12:57 UTC, Janix4000 commented on lib/membrane/compositor_element.ex
> +    :ok = Wgpu.put_video(wgpu_state, id, caps, position, z_value, scale)
Also, you can pass one struct with these options into the rustler NIF.

2022-11-30 12:57 UTC, Janix4000 commented on native/membrane_videocompositor/src/compositor/edge_rounder/mod.rs
> +                mask: !0,
Is it a negation of `0`?

2022-11-30 12:57 UTC, Janix4000 commented on native/membrane_videocompositor/src/compositor/edge_rounder/mod.rs
> +            render_pass.draw_indexed(0..INDICES.len() as u32, 0, 0..1);
I do not understand `0..INDICES.len() as u32` expression.
Isn't equivalent to `INDICES as u32`?

2022-11-30 12:57 UTC, Janix4000 commented on pipeline/lib/membrane/video_compositor/pipeline/utility/input_stream.ex
> +  defstruct caps: nil, z_value: nil, position: nil, scale: nil, input: nil
```suggestion
  @enforce_keys [:caps, :position, :scale, :input]
  defstruct @enforce_keys
```

2022-12-08 14:15 UTC, closed without merging