Fix screwed up tests
membraneframework-labs/membrane_video_compositor_plugin pull request #66
Opened 2022-11-28 16:29 UTC by WojciechBarczynski

2022-11-29 13:03 UTC, Janix4000 requested changes
You need to update videos' positions after this change (no further need to divide caps dimensions): https://github.com/membraneframework-labs/membrane_video_compositor_plugin/blob/5c2619e7f0ada2d40b186e221688e90bc5408658/test/pipeline_integration_test.exs#L65-L70

Additionally, it is an excellent opportunity to change the names of output videos to correspond real resolutions of the composed videos.

2022-11-30 13:47 UTC, Janix4000 requested changes
I renamed tests a little.

You can batch all of the suggestions into one commit.

2022-11-30 13:47 UTC, Janix4000 commented on test/composing_test.exs
>      @describetag :tmp_dir
```suggestion
  describe "Checks composition and raw video pipeline on merging four videos on 2x2 grid" do
    @describetag :tmp_dir
```

2022-11-30 13:47 UTC, Janix4000 commented on test/composing_test.exs
> +    test "3s 720p 1fps raw videos", %{tmp_dir: tmp_dir} do
```suggestion
    test "3s 720p 1fps raw", %{tmp_dir: tmp_dir} do
```

2022-11-30 13:47 UTC, Janix4000 commented on test/composing_test.exs
> +    test "10s 720p 1fps raw videos", %{tmp_dir: tmp_dir} do
```suggestion
    test "10s 720p 1fps raw", %{tmp_dir: tmp_dir} do
```

2022-11-30 13:47 UTC, Janix4000 commented on test/pipeline_integration_test.exs
> +  describe "Checks h264 pipeline on merging four" do
```suggestion
  describe "Checks h264 pipeline on merging four videos on 2x2 grid" do
```

2022-11-30 13:47 UTC, Janix4000 commented on test/pipeline_integration_test.exs
> +    test "2s 720p 30fps videos", %{tmp_dir: tmp_dir} do
```suggestion
    test "2s 720p 30fps h264", %{tmp_dir: tmp_dir} do
```

2022-11-30 13:47 UTC, Janix4000 commented on test/pipeline_integration_test.exs
> +    test "1s 1080p 30fps videos", %{tmp_dir: tmp_dir} do
```suggestion
    test "1s 1080p 30fps h264", %{tmp_dir: tmp_dir} do
```

2022-11-30 13:47 UTC, Janix4000 commented on test/pipeline_integration_test.exs
> +    test "30s 720p 30fps videos", %{tmp_dir: tmp_dir} do
```suggestion
    test "30s 720p 30fps h264", %{tmp_dir: tmp_dir} do
```

2022-11-30 13:47 UTC, Janix4000 commented on test/pipeline_integration_test.exs
> +    test "60s 1080p 30fps videos", %{tmp_dir: tmp_dir} do
```suggestion
    test "60s 1080p 30fps h264", %{tmp_dir: tmp_dir} do
```

2022-11-30 16:54 UTC, WojciechBarczynski commented on test/composing_test.exs
>      @describetag :tmp_dir
done

2022-11-30 16:54 UTC, WojciechBarczynski commented on test/composing_test.exs
> +    test "3s 720p 1fps raw videos", %{tmp_dir: tmp_dir} do
done

2022-11-30 16:54 UTC, WojciechBarczynski commented on test/composing_test.exs
> +    test "10s 720p 1fps raw videos", %{tmp_dir: tmp_dir} do
done

2022-11-30 16:55 UTC, WojciechBarczynski commented on test/pipeline_integration_test.exs
> +  describe "Checks h264 pipeline on merging four" do
done

2022-11-30 16:55 UTC, WojciechBarczynski commented on test/pipeline_integration_test.exs
> +    test "30s 720p 30fps videos", %{tmp_dir: tmp_dir} do
done

2022-12-01 13:32 UTC, Janix4000 approved these changes
Gooood...

2022-12-01 15:10 UTC, merged